language: go
go:
  - 1.x
before_install:
  - go get github.com/golang/lint/golint
  - go get -d ./...
script:
  - go build ./...
  - go vet ./...
  - golint -set_exit_status ./...
  - go test -v ./...
